config/routes.rb
Rails.application.routes.draw do

  get 'page/home'

  get 'page/search'

  get 'page/signup'

  get 'page/howitworks'

  get 'page/dlanding'

  get 'page/olanding'

  get 'page/dmanage'

  get 'page/omanage'

  get 'page/profile'

  get 'page/help'

  get 'page/contact'

  get 'page/leasing'

  get 'page/bookingdetails'

  get 'page/aboutus'

  get 'page/faq'

  get 'page/blog'

  get 'page/success1'

  get 'page/success2'

  get 'page/success3'

  get 'page/success4'

  get 'page/tnc'

  resources :rental_orders
  resources :parking_addresses
  resources :car_details
  root :to => 'users#index'
  resources :user_sessions
  resources :users

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  resources :users

  # define "/users_get" as a route that is handled by the users_controller function users_get
  get "users_get" => "users#users_get"

  # define "/users_post" as a POST route that is handled by the users_controller function users_post
  post "users_post", to: "users#users_post"

  # define "/rental_orders_get" as a route that is handled by the rental_orders_controller function rental_orders_get
  get "rental_orders_get" => "rental_orders#rental_orders_get"

  # define "/rental_orders_post" as a POST route that is handled by the rental_orders_controller function rental_orders_post
  post "rental_orders_post", to: "rental_orders#rental_orders_post"

  # define "/car_details_get" as a route that is handled by the car_details_controller function car_details_get
  get "car_details_get" => "car_details#car_details_get"

  # define "/car_details_post" as a POST route that is handled by the car_details_controller function car_details_post
  post "car_details_post", to: "car_details#car_details_post"

  # define "/parking_addresses_get" as a route that is handled by the parking_addresses_controller function parking_addresses_get
  get "parking_addresses_get" => "parking_addresses#parking_addresses_get"

  # define "/parking_addresses_post" as a POST route that is handled by the parking_addresses_controller function parking_addresses_post
  post "parking_addresses_post", to: "parking_addresses#parking_addresses_post"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/parking_addresses_controller.rb
class ParkingAddressesController < ApplicationController
  before_action :set_parking_address, only: [:show, :edit, :update, :destroy]

  # GET /parking_addresses
  # GET /parking_addresses.json
  def index
    @parking_addresses = ParkingAddress.all
  end

  # GET /parking_addresses/1
  # GET /parking_addresses/1.json
  def show
  end

  # GET /parking_addresses/new
  def new
    @parking_address = ParkingAddress.new
  end

  # GET /parking_addresses/1/edit
  def edit
  end

  # POST /parking_addresses
  # POST /parking_addresses.json
  def create
    @parking_address = ParkingAddress.new(parking_address_params)

    respond_to do |format|
      if @parking_address.save
        format.html { redirect_to @parking_address, notice: 'Parking address was successfully created.' }
        format.json { render :show, status: :created, location: @parking_address }
      else
        format.html { render :new }
        format.json { render json: @parking_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parking_addresses/1
  # PATCH/PUT /parking_addresses/1.json
  def update
    respond_to do |format|
      if @parking_address.update(parking_address_params)
        format.html { redirect_to @parking_address, notice: 'Parking address was successfully updated.' }
        format.json { render :show, status: :ok, location: @parking_address }
      else
        format.html { render :edit }
        format.json { render json: @parking_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parking_addresses/1
  # DELETE /parking_addresses/1.json
  def destroy
    @parking_address.destroy
    respond_to do |format|
      format.html { redirect_to parking_addresses_url, notice: 'Parking address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parking_address
      @parking_address = ParkingAddress.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parking_address_params
      params.require(:parking_address).permit(:user_id, :address, :building, :city, :state, :country, :postcode, :additionalDetails, :monthlyRate, :weeklyRate, :dailyRate, :hourlyRate, :xCoordinates, :yCoordinate, :approval, :features, :status, :availableFrom)
    end
end

app/helpers/parking_addresses_helper.rb
module ParkingAddressesHelper
end

app/views/parking_addresses/_form.html.erb
<%= form_for(parking_address) do |f| %>
  <% if parking_address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(parking_address.errors.count, "error") %> prohibited this parking_address from being saved:</h2>

      <ul>
      <% parking_address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :building %>
    <%= f.text_field :building %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :country %>
    <%= f.text_field :country %>
  </div>

  <div class="field">
    <%= f.label :postcode %>
    <%= f.text_field :postcode %>
  </div>

  <div class="field">
    <%= f.label :additionalDetails %>
    <%= f.text_field :additionalDetails %>
  </div>

  <div class="field">
    <%= f.label :monthlyRate %>
    <%= f.text_field :monthlyRate %>
  </div>

  <div class="field">
    <%= f.label :weeklyRate %>
    <%= f.text_field :weeklyRate %>
  </div>

  <div class="field">
    <%= f.label :dailyRate %>
    <%= f.text_field :dailyRate %>
  </div>

  <div class="field">
    <%= f.label :hourlyRate %>
    <%= f.text_field :hourlyRate %>
  </div>

  <div class="field">
    <%= f.label :xCoordinates %>
    <%= f.text_field :xCoordinates %>
  </div>

  <div class="field">
    <%= f.label :yCoordinate %>
    <%= f.text_field :yCoordinate %>
  </div>

  <div class="field">
    <%= f.label :approval %>
    <%= f.check_box :approval %>
  </div>

  <div class="field">
    <%= f.label :features %>
    <%= f.text_field :features %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.check_box :status %>
  </div>

  <div class="field">
    <%= f.label :availableFrom %>
    <%= f.datetime_select :availableFrom %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parking_addresses/edit.html.erb
<h1>Editing Parking Address</h1>

<%= render 'form', parking_address: @parking_address %>

<%= link_to 'Show', @parking_address %> |
<%= link_to 'Back', parking_addresses_path %>

app/views/parking_addresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Parking Addresses</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Address</th>
      <th>Building</th>
      <th>City</th>
      <th>State</th>
      <th>Country</th>
      <th>Postcode</th>
      <th>Additionaldetails</th>
      <th>Monthlyrate</th>
      <th>Weeklyrate</th>
      <th>Dailyrate</th>
      <th>Hourlyrate</th>
      <th>Xcoordinates</th>
      <th>Ycoordinate</th>
      <th>Approval</th>
      <th>Features</th>
      <th>Status</th>
      <th>Availablefrom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parking_addresses.each do |parking_address| %>
      <tr>
        <td><%= parking_address.user %></td>
        <td><%= parking_address.address %></td>
        <td><%= parking_address.building %></td>
        <td><%= parking_address.city %></td>
        <td><%= parking_address.state %></td>
        <td><%= parking_address.country %></td>
        <td><%= parking_address.postcode %></td>
        <td><%= parking_address.additionalDetails %></td>
        <td><%= parking_address.monthlyRate %></td>
        <td><%= parking_address.weeklyRate %></td>
        <td><%= parking_address.dailyRate %></td>
        <td><%= parking_address.hourlyRate %></td>
        <td><%= parking_address.xCoordinates %></td>
        <td><%= parking_address.yCoordinate %></td>
        <td><%= parking_address.approval %></td>
        <td><%= parking_address.features %></td>
        <td><%= parking_address.status %></td>
        <td><%= parking_address.availableFrom %></td>
        <td><%= link_to 'Show', parking_address %></td>
        <td><%= link_to 'Edit', edit_parking_address_path(parking_address) %></td>
        <td><%= link_to 'Destroy', parking_address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Parking Address', new_parking_address_path %>

app/views/parking_addresses/new.html.erb
<h1>New Parking Address</h1>

<%= render 'form', parking_address: @parking_address %>

<%= link_to 'Back', parking_addresses_path %>

app/views/parking_addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @parking_address.user %>
</p>

<p>
  <strong>Address:</strong>
  <%= @parking_address.address %>
</p>

<p>
  <strong>Building:</strong>
  <%= @parking_address.building %>
</p>

<p>
  <strong>City:</strong>
  <%= @parking_address.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @parking_address.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @parking_address.country %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @parking_address.postcode %>
</p>

<p>
  <strong>Additionaldetails:</strong>
  <%= @parking_address.additionalDetails %>
</p>

<p>
  <strong>Monthlyrate:</strong>
  <%= @parking_address.monthlyRate %>
</p>

<p>
  <strong>Weeklyrate:</strong>
  <%= @parking_address.weeklyRate %>
</p>

<p>
  <strong>Dailyrate:</strong>
  <%= @parking_address.dailyRate %>
</p>

<p>
  <strong>Hourlyrate:</strong>
  <%= @parking_address.hourlyRate %>
</p>

<p>
  <strong>Xcoordinates:</strong>
  <%= @parking_address.xCoordinates %>
</p>

<p>
  <strong>Ycoordinate:</strong>
  <%= @parking_address.yCoordinate %>
</p>

<p>
  <strong>Approval:</strong>
  <%= @parking_address.approval %>
</p>

<p>
  <strong>Features:</strong>
  <%= @parking_address.features %>
</p>

<p>
  <strong>Status:</strong>
  <%= @parking_address.status %>
</p>

<p>
  <strong>Availablefrom:</strong>
  <%= @parking_address.availableFrom %>
</p>

<%= link_to 'Edit', edit_parking_address_path(@parking_address) %> |
<%= link_to 'Back', parking_addresses_path %>