config/routes.rb
Rails.application.routes.draw do

  get 'page/home'

  get 'page/search'

  get 'page/signup'

  get 'page/howitworks'

  get 'page/dlanding'

  get 'page/olanding'

  get 'page/dmanage'

  get 'page/omanage'

  get 'page/profile'

  get 'page/help'

  get 'page/contact'

  get 'page/leasing'

  get 'page/bookingdetails'

  get 'page/aboutus'

  get 'page/faq'

  get 'page/blog'

  get 'page/success1'

  get 'page/success2'

  get 'page/success3'

  get 'page/success4'

  get 'page/tnc'

  resources :rental_orders
  resources :parking_addresses
  resources :car_details
  root :to => 'users#index'
  resources :user_sessions
  resources :users

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  resources :users

  # define "/users_get" as a route that is handled by the users_controller function users_get
  get "users_get" => "users#users_get"

  # define "/users_post" as a POST route that is handled by the users_controller function users_post
  post "users_post", to: "users#users_post"

  # define "/rental_orders_get" as a route that is handled by the rental_orders_controller function rental_orders_get
  get "rental_orders_get" => "rental_orders#rental_orders_get"

  # define "/rental_orders_post" as a POST route that is handled by the rental_orders_controller function rental_orders_post
  post "rental_orders_post", to: "rental_orders#rental_orders_post"

  # define "/car_details_get" as a route that is handled by the car_details_controller function car_details_get
  get "car_details_get" => "car_details#car_details_get"

  # define "/car_details_post" as a POST route that is handled by the car_details_controller function car_details_post
  post "car_details_post", to: "car_details#car_details_post"

  # define "/parking_addresses_get" as a route that is handled by the parking_addresses_controller function parking_addresses_get
  get "parking_addresses_get" => "parking_addresses#parking_addresses_get"

  # define "/parking_addresses_post" as a POST route that is handled by the parking_addresses_controller function parking_addresses_post
  post "parking_addresses_post", to: "parking_addresses#parking_addresses_post"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/car_detail.rb
class CarDetail < ApplicationRecord
  belongs_to :user
  has_many :RentalOrder, :dependent => :destroy
  validates :carRegistrationNumber, uniqueness: true
  validates  :roadTaxNumber, uniqueness: true

  def self.find_by_userid(userid)
		CarDetail.where("user_id = ?", userid)
  end

  def self.cardetail_id(id)
  		CarDetail.where("id = ?", id)
  end
end

app/controllers/car_details_controller.rb
class CarDetailsController < ApplicationController
  before_action :set_car_detail, only: [:show, :edit, :update, :destroy]

  # GET /car_details
  # GET /car_details.json
  def index
    @car_details = CarDetail.all
  end

  # GET /car_details/1
  # GET /car_details/1.json
  def show
  end

  # GET /car_details/new
  def new
    @car_detail = CarDetail.new
  end

  # GET /car_details/1/edit
  def edit
  end

  # POST /car_details
  # POST /car_details.json
  def create
    @car_detail = CarDetail.new(car_detail_params)

    respond_to do |format|
      if @car_detail.save
        format.html { redirect_to @car_detail, notice: 'Car detail was successfully created.' }
        format.json { render :show, status: :created, location: @car_detail }
      else
        format.html { render :new }
        format.json { render json: @car_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /car_details/1
  # PATCH/PUT /car_details/1.json
  def update
    respond_to do |format|
      if @car_detail.update(car_detail_params)
        format.html { redirect_to @car_detail, notice: 'Car detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @car_detail }
      else
        format.html { render :edit }
        format.json { render json: @car_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /car_details/1
  # DELETE /car_details/1.json
  def destroy
    @car_detail.destroy
    respond_to do |format|
      format.html { redirect_to car_details_url, notice: 'Car detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car_detail
      @car_detail = CarDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_detail_params
      params.require(:car_detail).permit(:user_id, :carRegistrationNumber, :manufacturer, :model, :color, :roadTaxNumber)
    end
end

app/helpers/car_details_helper.rb
module CarDetailsHelper
end

app/views/car_details/_form.html.erb
<%= form_for(car_detail) do |f| %>
  <% if car_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car_detail.errors.count, "error") %> prohibited this car_detail from being saved:</h2>

      <ul>
      <% car_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :carRegistrationNumber %>
    <%= f.text_field :carRegistrationNumber %>
  </div>

  <div class="field">
    <%= f.label :manufacturer %>
    <%= f.text_field :manufacturer %>
  </div>

  <div class="field">
    <%= f.label :model %>
    <%= f.text_field :model %>
  </div>

  <div class="field">
    <%= f.label :color %>
    <%= f.text_field :color %>
  </div>

  <div class="field">
    <%= f.label :roadTaxNumber %>
    <%= f.text_field :roadTaxNumber %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/car_details/edit.html.erb
<h1>Editing Car Detail</h1>

<%= render 'form', car_detail: @car_detail %>

<%= link_to 'Show', @car_detail %> |
<%= link_to 'Back', car_details_path %>

app/views/car_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Car Details</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Carregistrationnumber</th>
      <th>Manufacturer</th>
      <th>Model</th>
      <th>Color</th>
      <th>Roadtaxnumber</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @car_details.each do |car_detail| %>
      <tr>
        <td><%= car_detail.user %></td>
        <td><%= car_detail.carRegistrationNumber %></td>
        <td><%= car_detail.manufacturer %></td>
        <td><%= car_detail.model %></td>
        <td><%= car_detail.color %></td>
        <td><%= car_detail.roadTaxNumber %></td>
        <td><%= link_to 'Show', car_detail %></td>
        <td><%= link_to 'Edit', edit_car_detail_path(car_detail) %></td>
        <td><%= link_to 'Destroy', car_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car Detail', new_car_detail_path %>

app/views/car_details/new.html.erb
<h1>New Car Detail</h1>

<%= render 'form', car_detail: @car_detail %>

<%= link_to 'Back', car_details_path %>

app/views/car_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @car_detail.user %>
</p>

<p>
  <strong>Carregistrationnumber:</strong>
  <%= @car_detail.carRegistrationNumber %>
</p>

<p>
  <strong>Manufacturer:</strong>
  <%= @car_detail.manufacturer %>
</p>

<p>
  <strong>Model:</strong>
  <%= @car_detail.model %>
</p>

<p>
  <strong>Color:</strong>
  <%= @car_detail.color %>
</p>

<p>
  <strong>Roadtaxnumber:</strong>
  <%= @car_detail.roadTaxNumber %>
</p>

<%= link_to 'Edit', edit_car_detail_path(@car_detail) %> |
<%= link_to 'Back', car_details_path %>