config/routes.rb
Rails.application.routes.draw do

  get 'page/home'

  get 'page/search'

  get 'page/signup'

  get 'page/howitworks'

  get 'page/dlanding'

  get 'page/olanding'

  get 'page/dmanage'

  get 'page/omanage'

  get 'page/profile'

  get 'page/help'

  get 'page/contact'

  get 'page/leasing'

  get 'page/bookingdetails'

  get 'page/aboutus'

  get 'page/faq'

  get 'page/blog'

  get 'page/success1'

  get 'page/success2'

  get 'page/success3'

  get 'page/success4'

  get 'page/tnc'

  resources :rental_orders
  resources :parking_addresses
  resources :car_details
  root :to => 'users#index'
  resources :user_sessions
  resources :users

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  resources :users

  # define "/users_get" as a route that is handled by the users_controller function users_get
  get "users_get" => "users#users_get"

  # define "/users_post" as a POST route that is handled by the users_controller function users_post
  post "users_post", to: "users#users_post"

  # define "/rental_orders_get" as a route that is handled by the rental_orders_controller function rental_orders_get
  get "rental_orders_get" => "rental_orders#rental_orders_get"

  # define "/rental_orders_post" as a POST route that is handled by the rental_orders_controller function rental_orders_post
  post "rental_orders_post", to: "rental_orders#rental_orders_post"

  # define "/car_details_get" as a route that is handled by the car_details_controller function car_details_get
  get "car_details_get" => "car_details#car_details_get"

  # define "/car_details_post" as a POST route that is handled by the car_details_controller function car_details_post
  post "car_details_post", to: "car_details#car_details_post"

  # define "/parking_addresses_get" as a route that is handled by the parking_addresses_controller function parking_addresses_get
  get "parking_addresses_get" => "parking_addresses#parking_addresses_get"

  # define "/parking_addresses_post" as a POST route that is handled by the parking_addresses_controller function parking_addresses_post
  post "parking_addresses_post", to: "parking_addresses#parking_addresses_post"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/rental_order.rb
class RentalOrder < ApplicationRecord
  belongs_to :ParkingAddress
  belongs_to :user

  def self.find_by_userid(userid)
	RentalOrder.where("user_id = ?", userid)#.find_by_parkinguserid(userid)
  end

  def self.find_by_parkinguserid(userid)
  	ParkingAddress.where("user_id = ?", userid)
  end

  def self.currentrentalMade(rentalid)
  	RentalOrder.where("user_id = ?", rentalid).where("rentStart >= ?", Time.now).where("rentEnd <= ?", Time.now)
  end

  def self.currentrentalReceived(rentalReceivedid)
  	RentalOrder.where("ParkingAddress_id = ?", rentalReceivedid).where("rentStart >= ?", Time.now).where("rentEnd <= ?", Time.now)
  end

  def self.rentalorder_id(id)
  	RentalOrder.find_by("id = ?", id)
  end

  def self.bookingsMadeAmount(userid)
  	RentalOrder.where("user_id = ?", userid).count
  end

  def self.bookingsReceivedAmount(userid)
  	i = 0
  	user = find_by_parkinguserid(userid)
  	amount = 0
	while i < user.size do
		value = RentalOrder.where("ParkingAddress_id = ?", user[i].id).count
  		amount = value + amount
  		i += 1
  	end
  	return amount
  end

  def self.find_rentedparking(userid)
  	i = 0
  	user = find_by_parkinguserid(userid)
  	rent = []
	while i < user.size do
  		rent.push RentalOrder.where("ParkingAddress_id = ?", user[i].id)
  		i += 1
  	end
  	return rent
  end

  def self.rentalTotal(rentalid)
  	rent = rentalorder_id(rentalid)

  	rentTotalHour = (rent.rentEnd.to_i - rent.rentStart.to_i)
  	rentmodulus = rentTotalHour % 3600
    rentPA = ParkingAddress.find_by("id = ?", rent.ParkingAddress_id)

  	rentTotalHourly = rent.rentEnd.hour - rent.rentStart.hour
  	rentTotalWeekly = (rent.rentEnd.day - rent.rentStart.day) / 7
  	rentTotalDaily = (rent.rentEnd.day - rent.rentStart.day) - (7 * rentTotalWeekly)
  	rentTotalMonthly = ((rent.rentEnd.year * 12 + rent.rentEnd.month) - (rent.rentStart.year * 12 + rent.rentStart.month))
  	rentTotalYearly = rent.rentEnd.year - rent.rentStart.year

  	if rentTotalHour > 0 && rentTotalHour < 3600
  		rentTotal = rentPA.hourlyRate
  	else 
		rentTotal = (rentTotalYearly * rentPA.montlyRate * 12) +  (rentTotalMonthly * rentPA.montlyRate) + (rentTotalWeekly * rentPA.weeklyRate) + (rentTotalDaily * rentPA.dailyRate) + (rentTotalHourly * rentPA.hourlyRate)
		if rentmodulus != 0
			rentTotal = rentTotal + rentPA.hourlyRate
		end
  	end
  	RentalOrder.where("id = ?", rentalid).update_all(orderTotal: rentTotal)
  end

  def self.latestparking(rentalid)
    rent = RentalOrder.where("rentStart >= ?", Time.now).where("user_id = ?", rentalid).order("rentStart").first
    if rent.nil?
      rent = {rental_order: {id: "0",ParkingAddress: {id: "0",address: "0",city: "0",state: "0",country: "0",zipcode: "0",additionalDetails: "0",montlyRate: "0",weeklyRate: "0",dailyRate: "0",hourlyRate: "0",xCoordinate: "0",yCoordinate: "0",approval: "0",user: {id: "0",email: "0",firstName: "0",lastName: "0",gender: "0",age: "0",indentificationCardNumber: "0",driverLicense: "0"}},user: {id: "0",email: "0",firstName: "0",lastName: "0",gender: "0",age: "0",indentificationCardNumber: "0",driverLicense: "0"},rentStart: "0",rentEnd: "0",orderTotal: "0",orderStatus: "0"}}
      return rent.to_json
    else
      return rent
    end
  end

  def self.updateuserid(userid)
    latestRent = RentalOrder.order("id").last
    puts "Latest Rent ID: " + latestRent.id.to_s
    final = RentalOrder.where("id = ?", latestRent.id).update_all(user_id: userid)
    return final
  end
end

app/controllers/rental_orders_controller.rb
class RentalOrdersController < ApplicationController
  before_action :set_rental_order, only: [:show, :edit, :update, :destroy]

  # GET /rental_orders
  # GET /rental_orders.json
  def index
    @rental_orders = RentalOrder.all
  end

  # GET /rental_orders/1
  # GET /rental_orders/1.json
  def show
  end

  # GET /rental_orders/new
  def new
    @rental_order = RentalOrder.new
  end

  # GET /rental_orders/1/edit
  def edit
  end

  # POST /rental_orders
  # POST /rental_orders.json
  def create
    @rental_order = RentalOrder.new(rental_order_params)

    respond_to do |format|
      if @rental_order.save
        format.html { redirect_to @rental_order, notice: 'Rental order was successfully created.' }
        format.json { render :show, status: :created, location: @rental_order }
      else
        format.html { render :new }
        format.json { render json: @rental_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rental_orders/1
  # PATCH/PUT /rental_orders/1.json
  def update
    respond_to do |format|
      if @rental_order.update(rental_order_params)
        format.html { redirect_to @rental_order, notice: 'Rental order was successfully updated.' }
        format.json { render :show, status: :ok, location: @rental_order }
      else
        format.html { render :edit }
        format.json { render json: @rental_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rental_orders/1
  # DELETE /rental_orders/1.json
  def destroy
    @rental_order.destroy
    respond_to do |format|
      format.html { redirect_to rental_orders_url, notice: 'Rental order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rental_order
      @rental_order = RentalOrder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rental_order_params
      params.require(:rental_order).permit(:parking_address_id, :user_id, :rentStart, :rentEnd, :orderTotal, :status)
    end
end

app/helpers/rental_orders_helper.rb
module RentalOrdersHelper
end

app/views/rental_orders/_form.html.erb
<%= form_for(rental_order) do |f| %>
  <% if rental_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rental_order.errors.count, "error") %> prohibited this rental_order from being saved:</h2>

      <ul>
      <% rental_order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :parking_address_id %>
    <%= f.text_field :parking_address_id %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :rentStart %>
    <%= f.datetime_select :rentStart %>
  </div>

  <div class="field">
    <%= f.label :rentEnd %>
    <%= f.datetime_select :rentEnd %>
  </div>

  <div class="field">
    <%= f.label :orderTotal %>
    <%= f.text_field :orderTotal %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.check_box :status %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rental_orders/edit.html.erb
<h1>Editing Rental Order</h1>

<%= render 'form', rental_order: @rental_order %>

<%= link_to 'Show', @rental_order %> |
<%= link_to 'Back', rental_orders_path %>

app/views/rental_orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rental Orders</h1>

<table>
  <thead>
    <tr>
      <th>Parking address</th>
      <th>User</th>
      <th>Rentstart</th>
      <th>Rentend</th>
      <th>Ordertotal</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rental_orders.each do |rental_order| %>
      <tr>
        <td><%= rental_order.parking_address %></td>
        <td><%= rental_order.user %></td>
        <td><%= rental_order.rentStart %></td>
        <td><%= rental_order.rentEnd %></td>
        <td><%= rental_order.orderTotal %></td>
        <td><%= rental_order.status %></td>
        <td><%= link_to 'Show', rental_order %></td>
        <td><%= link_to 'Edit', edit_rental_order_path(rental_order) %></td>
        <td><%= link_to 'Destroy', rental_order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rental Order', new_rental_order_path %>

app/views/rental_orders/new.html.erb
<h1>New Rental Order</h1>

<%= render 'form', rental_order: @rental_order %>

<%= link_to 'Back', rental_orders_path %>

app/views/rental_orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Parking address:</strong>
  <%= @rental_order.parking_address %>
</p>

<p>
  <strong>User:</strong>
  <%= @rental_order.user %>
</p>

<p>
  <strong>Rentstart:</strong>
  <%= @rental_order.rentStart %>
</p>

<p>
  <strong>Rentend:</strong>
  <%= @rental_order.rentEnd %>
</p>

<p>
  <strong>Ordertotal:</strong>
  <%= @rental_order.orderTotal %>
</p>

<p>
  <strong>Status:</strong>
  <%= @rental_order.status %>
</p>

<%= link_to 'Edit', edit_rental_order_path(@rental_order) %> |
<%= link_to 'Back', rental_orders_path %>